[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AK - Metadaten"
authors = [{name = "GDI", email = "INFO@GDI-DE.de"}]
dynamic = ["version", "description"]
